name: CD

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
  workflow_dispatch:

jobs:
  plan_terraform:
    name: Plan Terraform
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TFCLOUD_TOKEN }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Install mods
        uses: ./.github/actions/install-mods

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run terraform init
        working-directory: infra/
        run: terraform init -input=false

      - name: Run terraform plan
        working-directory: infra/
        env:
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          TF_VAR_public_ssh_key: ${{ secrets.PUBLIC_SSH_KEY }}
          TF_VAR_private_ssh_key: ${{ secrets.PRIVATE_SSH_KEY }}
          TF_VAR_rcon_password: ${{ secrets.RCON_PASSWORD }}
          TF_VAR_rcon_port: ${{ secrets.RCON_PORT }}
        run: terraform plan -no-color -out=tfplan

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: infra/tfplan
          retention-days: 5

  apply_terraform:
    name: Apply Terraform
    needs: plan_terraform
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TFCLOUD_TOKEN }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Install mods
        uses: ./.github/actions/install-mods

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run terraform init
        working-directory: infra/
        run: terraform init -input=false

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: infra/

      - name: Deploy to Hetzner
        working-directory: infra/
        env:
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          TF_VAR_public_ssh_key: ${{ secrets.PUBLIC_SSH_KEY }}
          TF_VAR_private_ssh_key: ${{ secrets.PRIVATE_SSH_KEY }}
          TF_VAR_rcon_password: ${{ secrets.RCON_PASSWORD }}
          TF_VAR_rcon_port: ${{ secrets.RCON_PORT }}
        run: terraform apply -no-color tfplan
