name: CD

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"

jobs:
  apply_terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TFCLOUD_TOKEN }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Install mods
        uses: ./.github/actions/install-mods

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run terraform init
        working-directory: infra/
        run: terraform init -input=false

      - name: Run terraform plan
        working-directory: infra/
        env:
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          TF_VAR_public_ssh_key: ${{ secrets.PUBLIC_SSH_KEY }}
          TF_VAR_private_ssh_key: ${{ secrets.PRIVATE_SSH_KEY }}
          TF_VAR_rcon_password: ${{ secrets.RCON_PASSWORD }}
          TF_VAR_rcon_port: ${{ secrets.RCON_PORT }}
        run: terraform plan -no-color

      - name: Deploy to Hetzner
        working-directory: infra/
        env:
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          TF_VAR_public_ssh_key: ${{ secrets.PUBLIC_SSH_KEY }}
          TF_VAR_private_ssh_key: ${{ secrets.PRIVATE_SSH_KEY }}
          TF_VAR_rcon_password: ${{ secrets.RCON_PASSWORD }}
          TF_VAR_rcon_port: ${{ secrets.RCON_PORT }}
        run: terraform apply -auto-approve -no-color
